Refactor get port config
rtlabs-com/p-net pull request #299
Opened 2021-01-13 08:03 UTC by pyhys

2021-01-13 08:22 UTC, olbjo approved these changes
I have reviewed commits 2 and 3. Only one minor comment.
👍

2021-01-13 08:22 UTC, olbjo commented on src/device/pf_cmina.h
> + * @param alias         In :   The alias name. Terminated string.
Missing tab

2021-01-13 11:02 UTC, fredrikdanielmoller requested changes

2021-01-14 14:34 UTC, pyhys commented on src/device/pf_cmina.h
> + * @param alias         In :   The alias name. Terminated string.
Done

2021-01-14 14:35 UTC, pyhys commented on src/device/pf_port.h
> + * @param net              InOut: The p-net stack instance
Done

2021-01-14 14:35 UTC, pyhys commented on src/device/pf_port.h
> + * @param net              InOut: The p-net stack instance
Done

2021-01-14 14:41 UTC, pyhys commented on src/device/pf_cmina.h
> + * @param alias         In :   The alias name. Terminated string.
Done

2021-01-14 14:41 UTC, pyhys commented on src/device/pf_cmina.h
> + *          -1 if an error occurred.
Refactored
Done

2021-01-14 14:41 UTC, pyhys commented on src/device/pf_cmina.h
> + *          -1 if an error occurred.
Refactored
Done

2021-01-14 14:42 UTC, pyhys commented on src/device/pf_cmina.h
> + *          -1 if an error occurred.
Refactored
Done

2021-01-14 14:42 UTC, pyhys commented on src/device/pf_cmina.h
> + * @param pp_alias         Out:   The alias name. Terminated string.
Refactored
Done

2021-01-14 14:42 UTC, pyhys commented on src/device/pf_cmina.h
>   * @param pp_station_name  Out:   The station name. Terminated string.
Refactored
Done

2021-01-14 14:42 UTC, pyhys commented on src/device/pf_cmina.c
> +   }
Done

2021-01-14 14:42 UTC, pyhys commented on src/device/pf_cmina.c
> + * Implement setters and getters for net->cmina_current_dcp_ase, so other parts
Done

2021-01-14 14:43 UTC, pyhys commented on src/device/pf_cmina.h
> + * Store the current alias name of the device.
Updated docs slightly
Done

2021-01-14 15:46 UTC, fredrikdanielmoller requested changes

2021-01-14 15:46 UTC, fredrikdanielmoller commented on src/device/pf_cmina.c
> +      sizeof (net->cmina_current_dcp_ase.station_name),
```suggestion
      PNET_STATION_NAME_MAX_SIZE,
```

2021-01-14 15:46 UTC, fredrikdanielmoller commented on src/device/pf_cmina.c
> +      sizeof (net->cmina_current_dcp_ase.alias_name),
```suggestion
      PF_ALIAS_MAX_SIZE,
```

2021-01-14 15:46 UTC, fredrikdanielmoller commented on src/device/pf_port.h
> + * @return Address to port configuration
```suggestion
 * @return Port configuration
```

2021-01-15 06:46 UTC, pyhys commented on src/device/pf_cmina.c
> +      sizeof (net->cmina_current_dcp_ase.station_name),
Done

2021-01-15 06:46 UTC, pyhys commented on src/device/pf_cmina.c
> +      sizeof (net->cmina_current_dcp_ase.alias_name),
Done

2021-01-15 06:46 UTC, pyhys commented on src/device/pf_port.h
> + * @return Address to port configuration
Done

2021-01-15 08:24 UTC, fredrikdanielmoller approved these changes

2021-01-19 15:04 UTC, merged